### PR TITLE
Fix issue with spreadsheets containing filters

### PR DESCRIPTION
**Pull request by coorasse**
This PR tackles and closes roo-rb#533 and roo-rb#276

### CODE REVIEW

**Comment by md5** [comment]
@kakubin any chance you could take a look at this PR? I'm in the process of updating one of our apps and saw that we're maintaining an internal fork of this gem that has nearly identical fix to this one.

Apologies if you're not the right person to ping, but I see that you've merged some recent PRs.

**Review by kakubin — APPROVED** [review]

**Comment by kakubin** [comment]
I've been removed my authority, so I honestly don't know what my role is.

**Comment by kakubin** [comment]
@patrickkulling Would you be willing to review it too?

**Comment by patrickkulling** [comment]
I will have a look later today

**Comment by md5** [comment]
Thanks @patrickkulling! It looks like there are a fair number of changes post-`v2.9.0` that would be helpful to get into a `v2.10.0` release. Any chance that is in the works?

**Comment by patrickkulling** [comment]
@md5 There is one additional PR that I would like to see back at least but I agree that we should be planning to release a new version of roo soon.

I will try to figure out how that has been done in the past.

**Pull request merged**
