### PR TITLE
Add additional formula cell types: Date, TrueClass, FalseClass

### PR DESCRIPTION
**Pull request by cybercode**
Title is self expanatory. `to_csv` fails due to missing formula result types:

- Date
- TrueClass
- FalseClass

### CODE REVIEW

**Comment by stevendaniels** [comment]
It looks like a good change. Could you add some tests that demonstrate the bad behavior?

**Comment by cybercode** [comment]
Added test, but it seems there was a major refactor on master two hours after i generated this pull request and alll the csv code has been moved out of `base.rb`! It's a one line change, I can't really spend hours on keeping up...

**Comment by stevendaniels** [comment]
@cybercode: Thanks for the update. Apologies for the conflicts caused. I added your changes to #367 and will merge them in soon.

**Comment by cybercode** [comment]
thanks. BTW, forgot to include this patch, which makes it **much** easier to track down the bad cells:

```
diff --git a/lib/roo/formatters/csv.rb b/lib/roo/formatters/csv.rb
index 3181f09..c062bf0 100644
--- a/lib/roo/formatters/csv.rb
+++ b/lib/roo/formatters/csv.rb
@@ -67,7 +67,7 @@ module Roo
           when Date, DateTime, TrueClass, FalseClass
             onecell.to_s
           else
-            fail "unhandled onecell-class #{onecell.class}"
+            fail "unhandled onecell-class #{onecell.class} (#{sheet}!#{row}:#{col})"
           end
         when :date, :datetime
           onecell.to_s
```

Should probably add it on line 79 as well...

**Pull request closed without merging**
