### PR TITLE
Fix :parse method with :clean option

### PR DESCRIPTION
**Pull request by stevendaniels**
- Fixes Roo::Excelx.parse method when using :clean option
 - Fixes Roo::CSV.parse method when using :clean option
 - Added tests for parse with :clean option

### CODE REVIEW

**Comment by stevendaniels** [comment]
See #182 and #183

**Comment by stevendaniels** [comment]
Travis failed because of a timeout, not because of a test case failing.

**Comment by reshleman** [comment]
@stevendaniels Thanks for taking this on. I just pulled down your branch and did a quick smoke test in `irb`, and this does appear to resolve #182 and resolve #183.

Thanks for your contributions to this gem! :+1:

**Comment by simonoff** [comment]
@stevendaniels can you fix JRuby?

**Comment by simonoff** [comment]
Oh... sorry, nevermind

**Pull request merged**
