### PR TITLE
Refactor test suite

### PR DESCRIPTION
**Pull request by pabloh**
Ok, this is not really a proper PR but more like a straw man proposal.

Currently the test suite is divided among `test/` and `spec/`, testing with both rspec and minitest/shoulda.

There's a single big file `test/roo_tests.rb` (2091 lines), where many different classes and functionalities are being tested and is littered with old comments written in German.

What I would like to propose (and eventually merge) is:

* Test only with rspec and delete minitest and shoulda related dependencies.
* Delete or translate to English every German comment remaining (this could also apply for the rest of the gem, but that's for another PR).
* Break up `test/roo_tests.rb`, into several files (each for every class/spreadsheet format) and test shared functionality using rspec's shared example groups.

So, what do you think?. Any comments, suggestions, warnings, additions or feedback about this?.

### CODE REVIEW

**Comment by simonoff** [comment]
Best variant is to rewritten tests from minitest to rspec. But it's tooo big task. So if you want you can split `roo_test.rb` on small files related to specific class.

**Comment by pabloh** [comment]
Maybe breaking down this into small PR's could also work.

**Comment by stevendaniels** [comment]
I don't think converting minitest to rspec is worth the effort. Reducing development dependencies isn't a big issue.

**Comment by pabloh** [comment]
Reducing development dependencies is just a side-effect, the main goal is to have a simpler and easier to maintain test suite.

**Comment by pabloh** [comment]
I'll see how far I can get without doing too much of a mess. Achieving some of the original goals at least partially would be beneficial anyway.

**Comment by stevendaniels** [comment]
@pabloh Thanks for working on simplifying the test suite. I agree that it's a bit convoluted and needs some refactoring. Any help refactoring the tests/specs is appreciated.

**Comment by pabloh** [comment]
@stevendaniels, OK, I would go forward with that. I also sent a PR, for moving some tests for the base spreadsheet to rspec though.

**Comment by stevendaniels** [comment]
Closing this request / converting to issue #243

**Pull request closed without merging**
